# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'azure-pipeline-pm(5e811388-da36-4a22-b49b-e3477f384ec3)'
    ScriptType: 'InlineScript'
    Inline: |
      gci env:\
    azurePowerShellVersion: 'LatestVersion'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-pipeline-pm(5e811388-da36-4a22-b49b-e3477f384ec3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'env'

