name: .NET Core CI 2
on:
  repository_dispatch:
    types: [matrix-ci]

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: ${{  github.event.client_payload.images }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
